blank_issues_enabled: false
contact_links:
  - name: General Account Support
    url: https://memerator.me/support
    about: If you have a problem specific to your account, or otherwise something personal, head here!
